name: wine-quality-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.5.2
    - pandas==2.2.3
    - numpy==1.26.4
    - azureml-defaults
    - inference-schema
